#!/usr/bin/env python3
"""What this lab costs, computed from the real schedule. Spends nothing.

    PYTHONPATH=src python scripts/estimate_credit_cost.py

Writes `data/outputs/cbb_credit_cost.md`. Touches no network and needs no
credential — the arithmetic must stay re-checkable by anyone, including CI,
which runs it on every push precisely so a market-list change that blows the
budget fails the build rather than the season.

## The billing rules, from the provider's documentation

* `/v4/sports`, `/v4/sports/{sport}/events` — free.
* `/v4/sports/{sport}/odds` — `markets x regions`, whole slate, one call.
* `/v4/sports/{sport}/events/{id}/odds` — `unique markets **returned** x
  regions`. An asked-for market nobody quotes costs nothing.
* `/v4/sports/{sport}/scores?daysFrom=N` — 2.
* every `/v4/historical/...` equivalent — **10x** the live rate.

Every figure below is the **pessimistic bound**: every asked-for market
returning at every book. The NHL lab's purchase was capped at 200,000 and spent
289,984 because it estimated from markets *asked* rather than markets
*returned*; the estimate here is deliberately the other way round, so the real
spend can only come in under it. The cap is separately enforced against the
measured running total read from `x-requests-last`.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd

from cbb_betting_lab import markets as M
from cbb_betting_lab import population as P
from cbb_betting_lab.competitions import CBB
from cbb_betting_lab.config import OUTPUTS_DIR, RAW_DIR
from cbb_betting_lab.providers.odds_api import (
    DEFAULT_REGIONS,
    HISTORICAL_MULTIPLIER,
)
from cbb_betting_lab.season import slate_date


REGIONS = len([r for r in DEFAULT_REGIONS.split(",") if r.strip()])

#: Provider-documented earliest historical snapshots for this sport, read from
#: the-odds-api.com/historical-odds-data on 2026-09-01.
FEATURED_HISTORY_FROM = "2020-11-16"
#: Everything beyond h2h/spreads/totals — props, halves, alternates — exists
#: historically only from this date, site-wide. It falls **after** the 2022-23
#: season ended, so the full catalogue is buyable for three seasons and no more.
ADDITIONAL_HISTORY_FROM = "2023-05-03"

#: What the sibling labs have committed, from their own `docs/credit_cost.md`
#: and CLAUDE.md. Same account, same pool: spending here spends there.
SIBLING_MONTHLY_COMMITMENTS = {
    "nhl-betting-lab": 26_091,   # 1,344 games, 19 per-event markets, one fetch a day
    "football-betting-lab": 10_084,  # the heaviest NFL/NHL overlap month
}

#: Cooper's standing authorisation, from the brief. Scaled down below if the
#: real quota will not carry it alongside the siblings' committed spend.
AUTHORISED_MONTHLY_CEILING = 1_500_000


def load_seasons(raw_dir: Path) -> dict[int, pd.DataFrame]:
    out: dict[int, pd.DataFrame] = {}
    directory = Path(raw_dir) / "cbb" / "schedules"
    for path in sorted(directory.glob("mbb_schedule_*.parquet")):
        season = int(path.stem.rsplit("_", 1)[-1])
        out[season] = pd.read_parquet(path)
    return out


def day_shape(schedule: pd.DataFrame) -> pd.Series:
    days = schedule["date"].map(
        lambda x: slate_date(pd.Timestamp(x).tz_convert("UTC").isoformat(), CBB)
    )
    return days.value_counts().sort_index()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--raw-dir", default=str(RAW_DIR))
    parser.add_argument("--quota-remaining", type=int, default=4_992_714)
    args = parser.parse_args(argv)

    seasons = load_seasons(Path(args.raw_dir))
    if not seasons:
        print("No cached schedules. Run scripts/fetch_cbb_data.py first.")
        return 1

    per_event_keys = M.per_event_provider_keys()
    bulk_keys = M.bulk_provider_keys()
    per_event_cost = len(per_event_keys) * REGIONS
    bulk_cost = len(bulk_keys) * REGIONS

    tier_costs = {}
    for tier in (1, 2, 3):
        keys = {k for t in range(1, tier + 1) for k in M.provider_keys_in_tier(t)}
        tier_costs[tier] = len(keys) * REGIONS * HISTORICAL_MULTIPLIER

    lines: list[str] = []
    add = lines.append
    add("# What this costs, and whether it fits")
    add("")
    add(
        "**Generated by `scripts/estimate_credit_cost.py` from the real cached "
        "schedule. It spends nothing and touches no network.** The reasoning "
        "that is not arithmetic lives in `docs/credit_cost.md`, because a "
        "finding appended to a regenerated file lasts exactly one re-run."
    )
    add("")
    add(
        f"Regions `{DEFAULT_REGIONS}` ({REGIONS}). Every figure is the "
        "**pessimistic bound** — every asked-for market returning at every "
        "book. Real spend can only come in under it, and is separately capped "
        "against the measured running total from `x-requests-last`."
    )
    add("")

    # --- the season's shape -------------------------------------------------
    add("## The season's shape, measured")
    add("")
    add(
        "| Season | Games | D-I v D-I | Non-D-I | Slate days | Mean/day | "
        "Median | **Peak day** |"
    )
    add("|---:|---:|---:|---:|---:|---:|---:|---:|")
    peak_overall = 0
    reference_season = 0
    for season in sorted(seasons):
        classified = P.classify(seasons[season])
        counts = P.count(classified)
        shape = day_shape(seasons[season])
        countable = counts.by_state.get("countable", 0) + counts.by_state.get(
            "scheduled", 0
        )
        non_di = counts.by_state.get("non_di_opponent", 0)
        peak = int(shape.max()) if len(shape) else 0
        if counts.by_state.get("countable", 0) and peak > peak_overall:
            peak_overall, reference_season = peak, season
        add(
            f"| {season} | {counts.total:,} | {countable:,} | {non_di:,} | "
            f"{len(shape)} | {len(seasons[season]) / max(len(shape), 1):.1f} | "
            f"{int(shape.median()) if len(shape) else 0} | **{peak}** |"
        )
    add("")
    add(
        f"The peak is **{peak_overall} games in one day**, in season "
        f"{reference_season}. That is opening Monday: the season's largest "
        "slate is its first, not a February Saturday. Every cap below is set "
        "against it, because **a cap below the worst slate is a cap that "
        "starves it, and a starved fetch and an unquoted market look identical "
        "in the reports.**"
    )
    add("")
    add(
        "**The 2027 row is a partial schedule, not a short season.** ESPN fills "
        "the calendar in over the autumn; 1,520 of its 1,629 rows still carry a "
        "midnight placeholder rather than a tip time. Every projection below "
        "uses the completed seasons for shape."
    )
    add("")

    # --- live cost ----------------------------------------------------------
    add("## Live fetching, per day and per season")
    add("")
    add(
        f"- Bulk call: **{len(bulk_keys)} featured keys x {REGIONS} regions = "
        f"{bulk_cost} credits**, whole slate, once per snapshot. On a "
        f"{peak_overall}-game day that is {peak_overall} games for {bulk_cost} "
        "credits, which is why the featured markets are never asked per event."
    )
    add(
        f"- Per event: **{len(per_event_keys)} keys x {REGIONS} regions = "
        f"{per_event_cost} credits** pessimistic — every ladder, half and prop "
        "returning at every book. In practice a low-major Tuesday game returns "
        "a handful, and an unquoted market costs nothing."
    )
    add("")
    add("| Snapshots/day | Peak day (pessimistic) | Peak day (featured only) |")
    add("|---:|---:|---:|")
    for snaps in (1, 2, 3):
        full = snaps * (bulk_cost + peak_overall * per_event_cost)
        featured = snaps * bulk_cost
        add(f"| {snaps} | {full:,} | {featured:,} |")
    add("")

    reference = seasons.get(2026, seasons[max(seasons)])
    ref_games = len(P.cardable(P.classify(reference)))
    ref_days = len(day_shape(reference))
    add(
        f"Over a full season ({ref_games:,} cardable games across {ref_days} "
        "slate days):"
    )
    add("")
    add("| Snapshots/day | Season, pessimistic | Season, featured only |")
    add("|---:|---:|---:|")
    for snaps in (1, 2, 3):
        full = snaps * (ref_days * bulk_cost + ref_games * per_event_cost)
        featured = snaps * ref_days * bulk_cost
        add(f"| {snaps} | {full:,} | {featured:,} |")
    add("")

    # --- historical ---------------------------------------------------------
    add("## Buying history")
    add("")
    add(
        f"Historical endpoints bill **{HISTORICAL_MULTIPLIER}x** the live rate. "
        "Two provider-documented cut-offs decide what is buyable at all:"
    )
    add("")
    add(
        f"- **Featured markets** (`h2h`, `spreads`, `totals`) exist from "
        f"**{FEATURED_HISTORY_FROM}** for `basketball_ncaab`."
    )
    add(
        f"- **Everything else** — props, halves, every alternate ladder — "
        f"exists from **{ADDITIONAL_HISTORY_FROM}**, site-wide. That date falls "
        "*after* the 2022-23 season ended, so **the full catalogue is buyable "
        "for three seasons and no more**: 2023-24, 2024-25 and 2025-26."
    )
    add("")
    add("| Tier | Keys | Credits/event | 3 seasons, 1 snapshot | 3 seasons, 2 snapshots |")
    add("|---:|---:|---:|---:|---:|")
    full_seasons = [s for s in (2024, 2025, 2026) if s in seasons]
    full_games = sum(
        len(P.cardable(P.classify(seasons[s]))) for s in full_seasons
    )
    for tier, cost in tier_costs.items():
        keys = len({k for t in range(1, tier + 1) for k in M.provider_keys_in_tier(t)})
        add(
            f"| 1-{tier} | {keys} | {cost:,} | {full_games * cost:,} | "
            f"{full_games * cost * 2:,} |"
        )
    add("")
    featured_seasons = [s for s in seasons if 2021 <= s <= 2026]
    featured_games = sum(
        len(P.cardable(P.classify(seasons[s]))) for s in featured_seasons
    )
    featured_hist = len(bulk_keys) * REGIONS * HISTORICAL_MULTIPLIER
    add(
        f"**Featured markets reach back further.** {featured_games:,} games "
        f"across seasons {min(featured_seasons)}-{max(featured_seasons)} at "
        f"{featured_hist} credits an event is "
        f"**{featured_games * featured_hist:,}** for one snapshot each — six "
        "seasons of moneyline, spread and total, which is the largest priced "
        "population any of these four labs has ever had."
    )
    add("")

    # --- the budget ---------------------------------------------------------
    sibling = sum(SIBLING_MONTHLY_COMMITMENTS.values())
    add("## Against the quota")
    add("")
    add(f"- **Quota remaining: {args.quota_remaining:,}**, read from ")
    add(
        f"  `x-requests-remaining` on {'a free `/v4/sports` call'}, 2026-09-01. "
        "Not documentation — the header."
    )
    add(f"- **Siblings' committed monthly spend: {sibling:,}**")
    for name, spend in sorted(SIBLING_MONTHLY_COMMITMENTS.items()):
        add(f"  - `{name}`: {spend:,}")
    add(
        f"- **Cooper's standing authorisation: {AUTHORISED_MONTHLY_CEILING:,} "
        "per calendar month** for this lab."
    )
    add("")
    headroom = args.quota_remaining - sibling * 5
    add(
        f"The heaviest thing this lab will ever do in one month is the "
        f"historical purchase. The full three-season, two-snapshot buy at tier "
        f"1-3 is **{full_games * tier_costs[3] * 2:,}** credits — which is more "
        f"than one month's authorisation, so it is bought in priority order "
        "across months: **core team markets across every season first, then "
        "ladders, then props, then futures.** That is Cooper's stated order and "
        "it is also the order of decreasing confidence that a market is quoted "
        "at all."
    )
    add("")
    add(
        f"Against {args.quota_remaining:,} remaining and roughly "
        f"{sibling * 5:,} committed to the siblings over a five-month college "
        f"season, there is about **{headroom:,}** of headroom. The live season "
        "at two snapshots a day is a rounding error inside it, and **no live "
        "in-season fetch can be starved by the purchase** because the purchase "
        "runs under its own cap in its own workflow and the card's fetch checks "
        "`x-requests-remaining` against its cap before it starts."
    )
    add("")
    add(
        "**A starved fetch and an unquoted market look identical.** The NHL "
        "lab's probe once reported its own starvation as market absence. Every "
        "report in this repository states the cap it ran under and the credits "
        "it actually spent, so the two can be told apart."
    )

    OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)
    target = OUTPUTS_DIR / CBB.output_name("credit_cost", ".md")
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")

    record = {
        "regions": REGIONS,
        "bulk_keys": list(bulk_keys),
        "per_event_keys": list(per_event_keys),
        "bulk_cost": bulk_cost,
        "per_event_cost_pessimistic": per_event_cost,
        "peak_games_in_a_day": peak_overall,
        "peak_day_season": reference_season,
        "daily_cap_needed_two_snapshots": 2
        * (bulk_cost + peak_overall * per_event_cost),
        "historical_cost_per_event_by_tier": tier_costs,
        "quota_remaining": args.quota_remaining,
    }
    (OUTPUTS_DIR / CBB.output_name("credit_cost", ".json")).write_text(
        json.dumps(record, indent=2) + "\n", encoding="utf-8"
    )

    print(f"Wrote {target}")
    print(
        f"Peak slate {peak_overall} games; two-snapshot daily cap needed: "
        f"{record['daily_cap_needed_two_snapshots']:,} credits."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
