"""Render the per-tier headline table into the hand-written documents.

**These two documents had no generator, and that is what every guard in
`tests/test_no_report_states_a_stale_correction.py` was built to compensate for.**
Four rounds of those guards were defeated in turn -- by a row count that looked
like a family size, by an ordinal, by a sentence terminator hidden behind a bold
marker, by a figure written in a spelling the guard did not enumerate. Each fix
made the inference cleverer; none of them made it right, because "which number
in this English sentence is a corrected interval, and which correction is it
stated at" is not a question a parser gets to answer.

A figure that is GENERATED cannot go stale, and needs no parsing at all. This
splices the table a reader actually acts on -- ROI and corrected interval per
tier, at the ledger's count as of this render -- between markers, exactly as
`run_why_the_model.py --splice-into` does for its own document.

The prose around it still argues, narrates and quotes superseded readings on
purpose; that is what these documents are for. Those figures carry an explicit
`[@N]`, and `test_every_interval_in_the_document_is_accounted_for` refuses any
interval it cannot account for, in any spelling. Between the two, nothing
stale is silent: the live numbers re-render, and the historical ones say so.

Usage:
    PYTHONPATH=src python scripts/splice_headline_table.py [--check]
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from cbb_betting_lab import stats as S  # noqa: E402

BEGIN_MARKER = "<!-- BEGIN GENERATED: headline_table -->"
END_MARKER = "<!-- END GENERATED -->"

DOCUMENTS = (REPO / "CLAUDE.md", REPO / "docs" / "project_status.md")
LEDGER = REPO / "data" / "outputs" / "experiment_ledger.json"
BACKTEST = REPO / "data" / "outputs" / "cbb_price_backtest.json"

TIERS = ("high_major", "mid_major", "low_major")


def render() -> str:
    """The table, from the record and the ledger, never from prose."""
    looks = len(json.loads(LEDGER.read_text(encoding="utf-8"))["hypotheses"])
    record = json.loads(BACKTEST.read_text(encoding="utf-8"))
    by_tier = {row["tier"]: row for row in record["by_tier"] if row.get("tier")}

    lines = [
        f"| Cut | Bets | ROI | Corrected (x{S.bonferroni_factor(looks):.4f}, "
        f"{looks} hypotheses) | Verdict |",
        "|:---|---:|---:|:---|:---|",
    ]
    for tier in TIERS:
        row = by_tier[tier]
        # **The verdict comes from `RoiInterval`, not from this file.** It was
        # re-implemented here as `high < 0 / low > 0 / else`, which omits the
        # declared 200-bet evidence floor -- so the generated table, which the
        # fence makes the trusted copy, could print "demonstrated deficit" on a
        # cell the record itself refuses as "not enough evidence", and
        # `test_the_committed_block_is_what_the_record_renders_to` would certify
        # it, because that test compares the fence to this render and never to
        # the record's own verdict. A generator that re-derives a rule is a
        # second implementation of it, and the second one is always the one
        # nobody re-reads.
        interval = S.RoiInterval(
            roi=row["roi"],
            low=row["low"],
            high=row["high"],
            bets=row["bets"],
            clusters=row["clusters"],
            standard_error=row["standard_error"],
            looks=looks,
            cluster_unit=row.get("cluster_unit", "game"),
        )
        lines.append(
            f"| {tier.replace('_', '-')} | {row['bets']:,} | {row['roi']:+.1%} | "
            f"{interval.adjusted_low * 100:+.1f}% to "
            f"{interval.adjusted_high * 100:+.1f}% | {interval.verdict()} |"
        )
    lines.append("")
    lines.append(
        f"*Generated by `scripts/splice_headline_table.py` from "
        f"`data/outputs/cbb_price_backtest.json` at the ledger's {looks} "
        "hypotheses. Do not edit between the markers; re-run the script.*"
    )
    return "\n".join(lines)


def fenced(text: str) -> str | None:
    start, stop = text.find(BEGIN_MARKER), text.find(END_MARKER)
    if start == -1 or stop == -1:
        return None
    return text[start + len(BEGIN_MARKER) : stop].strip("\n")


def splice(path: Path, body: str) -> bool:
    text = path.read_text(encoding="utf-8")
    start, stop = text.find(BEGIN_MARKER), text.find(END_MARKER)
    if start == -1 or stop == -1:
        raise SystemExit(
            f"{path.name} has no generated block. Add the markers around the "
            f"headline table:\n  {BEGIN_MARKER}\n  {END_MARKER}"
        )
    updated = (
        text[: start + len(BEGIN_MARKER)] + "\n\n" + body + "\n\n" + text[stop:]
    )
    if updated == text:
        return False
    path.write_text(updated, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if a document's block is not what render() produces",
    )
    arguments = parser.parse_args()

    body = render()
    stale = []
    for path in DOCUMENTS:
        if arguments.check:
            if fenced(path.read_text(encoding="utf-8")) != body:
                stale.append(path.name)
            continue
        print(f"{path.name}: {'rewritten' if splice(path, body) else 'unchanged'}")
    if stale:
        print(f"stale generated block in: {', '.join(stale)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
